# Generated by Django 4.2.5 on 2023-09-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
