# Generated by Django 4.2.5 on 2023-11-08 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_rename_customer_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
