# Generated by Django 4.2.5 on 2023-11-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_full_name_profile_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category1',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
