# Generated by Django 4.2.5 on 2023-11-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='firstapp.OrderItem', to='firstapp.product1'),
        ),
    ]
