# Generated by Django 4.2.5 on 2023-11-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_remove_order_payment_remove_orderitem_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment2',
        ),
    ]
