# Generated by Django 4.2.5 on 2023-12-02 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_profileuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='FullName',
            new_name='fullName',
        ),
    ]
