# Generated by Django 4.2.5 on 2024-02-13 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_rename_fullname_profileuser_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_product_name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('image', models.ImageField(upload_to='rental_product_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.category1')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.subcategory1')),
            ],
        ),
    ]
