# Generated by Django 4.2.5 on 2024-02-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0026_rentaladdtocart'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rental_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.rentalproduct')),
            ],
        ),
    ]
