# Generated by Django 4.2.5 on 2024-02-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_rentalorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='rental_products',
            field=models.ManyToManyField(through='firstapp.RentalOrderItem', to='firstapp.rentalproduct'),
        ),
    ]
